services:
  ws-scylla-1: &scylla-main
    image: scylladb/scylla:6.0.1
    container_name: ws-scylla-1
    command: ['--smp=1', '--memory=1GB', '--overprovisioned=1', '--developer-mode=1', '--seeds=ws-scylla-1']
    ports:
      - '9040:9042'
    networks:
      ws-scylla:
    volumes:
      - scylla-1:/var/lib/scylla
      - ./configs:/etc/scylla/configs
      - ./certificates:/etc/scylla/certs
    healthcheck:
      test: ['CMD-SHELL', 'cqlsh -e "SHOW VERSION" || exit 1']
      interval: 15s
      timeout: 30s
      retries: 15
      start_period: 30s
  ws-scylla-2: &scylla-replica
    <<: *scylla-main
    container_name: ws-scylla-2
    ports:
      - '9041:9042'
    volumes:
      - scylla-2:/var/lib/scylla
      - ./configs:/etc/scylla/configs
      - ./certificates:/etc/scylla/certs
  ws-scylla-3:
    <<: *scylla-replica
    container_name: ws-scylla-3
    ports:
      - '9042:9042'
    volumes:
      - scylla-3:/var/lib/scylla
      - ./configs:/etc/scylla/configs
      - ./certificates:/etc/scylla/certs
volumes:
  scylla-1:
    name: scylla-1
  scylla-2:
    name: scylla-2
  scylla-3:
    name: scylla-3
networks:
  ws-scylla:
    name: ws-scylla
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
          gateway: 10.10.5.1
    driver_opts:
      com.docker.network.bridge.name: ws-scylla
